services:
  - type: web
    name: artifact-hub
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: artifact-hub-db
          property: connectionString

databases:
  - name: artifact-hub-db
    plan: free
    databaseName: artifact_hub
    user: artifact_hub
