services:
  - type: web
    name: artifact-hub
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: AI_FEATURE_ENABLED
        value: "true"
      - key: AI_PROVIDER
        value: openai
      - key: PUBLIC_URL
        value: https://artifact-hub-y528.onrender.com
      - key: EMAIL_PROVIDER
        value: resend
      - key: EMAIL_FROM
        sync: false
      - key: FEEDBACK_EMAIL_TO
        value: contact@grafley.com
      - key: RESEND_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: artifact-hub-db
          property: connectionString

databases:
  - name: artifact-hub-db
    plan: free
    databaseName: artifact_hub
    user: artifact_hub
